Try to figure out the cause of
> Task :korim:jvmTest

DemoTest[jvm] > test[jvm] FAILED
    kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 40000 ms
        at (Coroutine boundary.()
        at com.soywiz.korim.format.AwtNativeImageFormatProvider.decodeInternal(NativeImageFormatProviderJvm.kt:28)

https://github.com/korlibs/korge/actions/runs/4131004145/jobs/7138249406#step:8:381